name: render drawio

on: [push, pull_request]

jobs:
  render_drawio:
    - uses: actions/checkout@v2
    - name: Convert digramm to png
      uses: Burnett01/actions-drawio@1.2
      with:
        src: diagramm.drawio
        dest: diagramm.png
